/** ASM Project Data - Generated: 2026. 1. 7. 오후 4:07:03 */
window.projectAsmData = [
  {
    "priority": "1",
    "customer": "ASMJ",
    "requestor": "Tanaka Koji",
    "category": "RFM",
    "model": "T.B.D",
    "pn": "T.B.D",
    "demand": "1",
    "specification": "2+60MHz / 3kW",
    "application": "PE-CVD",
    "dept": "R&D",
    "nbd": "2026-02-27",
    "progress": "OPEN"
  },
  {
    "priority": "1",
    "customer": "ASM",
    "requestor": "Estern Shin",
    "category": "CONTROLLER",
    "model": "AEPC-2448P-13M",
    "pn": "E212-13562",
    "demand": "2",
    "specification": "2+13MHz / E-CAT",
    "application": "PE-ALD",
    "dept": "R&D",
    "nbd": "2026-01-09",
    "progress": "FINISHED"
  },
  {
    "priority": "1",
    "customer": "ASM",
    "requestor": "Estern Shin",
    "category": "CONTROLLER",
    "model": "AEPC-2448P-13M",
    "pn": "D212-13562",
    "demand": "2",
    "specification": "2+13MHz / D-NET",
    "application": "PE-ALD",
    "dept": "R&D",
    "nbd": "2026-01-09",
    "progress": "FINISHED"
  },
  {
    "priority": "1",
    "customer": "ASM",
    "requestor": "Estern Shin",
    "category": "CONTROLLER",
    "model": "AEPC-2448P-60M",
    "pn": "D212-60430",
    "demand": "2",
    "specification": "2+60MHz / D-NET",
    "application": "PE-ALD",
    "dept": "R&D",
    "nbd": "2026-01-09",
    "progress": "FINISHED"
  },
  {
    "priority": "2",
    "customer": "ASM",
    "requestor": "Estern Shin",
    "category": "RFG",
    "model": "MP12M-20",
    "pn": "A120-30000",
    "demand": "4",
    "specification": "2MHz / 1.2kW / E-CAT",
    "application": "Arius CX",
    "dept": "MFG",
    "nbd": "2026-02-26",
    "progress": "OPEN"
  },
  {
    "priority": "2",
    "customer": "ASM",
    "requestor": "Estern Shin",
    "category": "RFG",
    "model": "MP12M-20",
    "pn": "A120-40000",
    "demand": "4",
    "specification": "2MHz / 1.2kW / D-NET",
    "application": "Magma SX+",
    "dept": "MFG",
    "nbd": "2026-02-26",
    "progress": "OPEN"
  },
  {
    "priority": "2",
    "customer": "ASM",
    "requestor": "Estern Shin",
    "category": "RFG",
    "model": "APG-2060HG-D",
    "pn": "1232-016-01",
    "demand": "2",
    "specification": "60MHz / 2kW",
    "application": "PHX DEMO",
    "dept": "MFG",
    "nbd": "2026-02-23",
    "progress": "OPEN"
  },
  {
    "priority": "2",
    "customer": "ASM",
    "requestor": "Estern Shin",
    "category": "RFG",
    "model": "APG-2012HD",
    "pn": "1229-207-01",
    "demand": "1",
    "specification": "12.9MHz / 2kW",
    "application": "PHX DEMO",
    "dept": "MFG",
    "nbd": "2026-02-23",
    "progress": "FINISHED"
  },
  {
    "priority": "2",
    "customer": "ASM",
    "requestor": "Estern Shin",
    "category": "RFG",
    "model": "AGL-1004HD",
    "pn": "1213-686-01",
    "demand": "1",
    "specification": "430kHz / 1kW",
    "application": "PHX DEMO",
    "dept": "MFG",
    "nbd": "2026-02-23",
    "progress": "OPEN"
  },
  {
    "priority": "2",
    "customer": "ASM",
    "requestor": "Estern Shin",
    "category": "RFG",
    "model": "APG-2060HG",
    "pn": "1236-414-01",
    "demand": "2",
    "specification": "60MHz / 2kW",
    "application": "SPARE",
    "dept": "MFG",
    "nbd": "2026-02-23",
    "progress": "OPEN"
  },
  {
    "priority": "3",
    "customer": "ASM",
    "requestor": "Estern Shin",
    "category": "RFG",
    "model": "AFD6004-AAK R3",
    "pn": "1267-424-01",
    "demand": "2",
    "specification": "0.43+60MHz / 3kW",
    "application": "SPARE",
    "dept": "MFG",
    "nbd": "2026-02-23",
    "progress": "OPEN"
  },
  {
    "priority": "1",
    "customer": "ASM",
    "requestor": "Estern Shin",
    "category": "RFG",
    "model": "APG-1013HGH",
    "pn": "A0126-PG00165",
    "demand": "5",
    "specification": "13.56MHz / 1kW / High Accuracy",
    "application": "ASMA EPITAXY",
    "dept": "R&D",
    "nbd": "2026-03-13",
    "progress": "OPEN"
  },
  {
    "priority": "1",
    "customer": "ASM",
    "requestor": "Estern Shin",
    "category": "RFG",
    "model": "AGL-1204HG",
    "pn": "1231-295-01",
    "demand": "2",
    "specification": "430kHz / 1.2kW / E-CAT",
    "application": "ASMA EPITAXY",
    "dept": "MFG",
    "nbd": "2026-02-06",
    "progress": "FINISHED"
  },
  {
    "priority": "1",
    "customer": "ASM",
    "requestor": "Estern Shin",
    "category": "RFG",
    "model": "MP12M-20",
    "pn": "A120-30000",
    "demand": "2",
    "specification": "2MHz / 1.2kW /E-CAT",
    "application": "ASMA EPITAXY",
    "dept": "MFG",
    "nbd": "2026-03-13",
    "progress": "OPEN"
  },
  {
    "priority": "1",
    "customer": "ASM",
    "requestor": "Estern Shin",
    "category": "CONTROLLER",
    "model": "AEPC-2448P-13M",
    "pn": "E212-13562",
    "demand": "1",
    "specification": "2+13MHz / E-CAT",
    "application": "ASMA EPITAXY",
    "dept": "R&D",
    "nbd": "2026-02-06",
    "progress": "OPEN"
  },
  {
    "priority": "",
    "customer": "",
    "requestor": "",
    "category": "",
    "model": "",
    "pn": "",
    "demand": "",
    "specification": "",
    "application": "",
    "dept": "",
    "nbd": "",
    "progress": ""
  },
  {
    "priority": "",
    "customer": "",
    "requestor": "",
    "category": "",
    "model": "",
    "pn": "",
    "demand": "",
    "specification": "",
    "application": "",
    "dept": "",
    "nbd": "",
    "progress": ""
  },
  {
    "priority": "",
    "customer": "",
    "requestor": "",
    "category": "",
    "model": "",
    "pn": "",
    "demand": "",
    "specification": "",
    "application": "",
    "dept": "",
    "nbd": "",
    "progress": ""
  },
  {
    "priority": "",
    "customer": "",
    "requestor": "",
    "category": "",
    "model": "",
    "pn": "",
    "demand": "",
    "specification": "",
    "application": "",
    "dept": "",
    "nbd": "",
    "progress": ""
  },
  {
    "priority": "",
    "customer": "",
    "requestor": "",
    "category": "",
    "model": "",
    "pn": "",
    "demand": "",
    "specification": "",
    "application": "",
    "dept": "",
    "nbd": "",
    "progress": ""
  },
  {
    "priority": "",
    "customer": "",
    "requestor": "",
    "category": "",
    "model": "",
    "pn": "",
    "demand": "",
    "specification": "",
    "application": "",
    "dept": "",
    "nbd": "",
    "progress": ""
  },
  {
    "priority": "",
    "customer": "",
    "requestor": "",
    "category": "",
    "model": "",
    "pn": "",
    "demand": "",
    "specification": "",
    "application": "",
    "dept": "",
    "nbd": "",
    "progress": ""
  },
  {
    "priority": "",
    "customer": "",
    "requestor": "",
    "category": "",
    "model": "",
    "pn": "",
    "demand": "",
    "specification": "",
    "application": "",
    "dept": "",
    "nbd": "",
    "progress": ""
  },
  {
    "priority": "",
    "customer": "",
    "requestor": "",
    "category": "",
    "model": "",
    "pn": "",
    "demand": "",
    "specification": "",
    "application": "",
    "dept": "",
    "nbd": "",
    "progress": ""
  },
  {
    "priority": "",
    "customer": "",
    "requestor": "",
    "category": "",
    "model": "",
    "pn": "",
    "demand": "",
    "specification": "",
    "application": "",
    "dept": "",
    "nbd": "",
    "progress": ""
  },
  {
    "priority": "",
    "customer": "",
    "requestor": "",
    "category": "",
    "model": "",
    "pn": "",
    "demand": "",
    "specification": "",
    "application": "",
    "dept": "",
    "nbd": "",
    "progress": ""
  },
  {
    "priority": "",
    "customer": "",
    "requestor": "",
    "category": "",
    "model": "",
    "pn": "",
    "demand": "",
    "specification": "",
    "application": "",
    "dept": "",
    "nbd": "",
    "progress": ""
  },
  {
    "priority": "",
    "customer": "",
    "requestor": "",
    "category": "",
    "model": "",
    "pn": "",
    "demand": "",
    "specification": "",
    "application": "",
    "dept": "",
    "nbd": "",
    "progress": ""
  },
  {
    "priority": "",
    "customer": "",
    "requestor": "",
    "category": "",
    "model": "",
    "pn": "",
    "demand": "",
    "specification": "",
    "application": "",
    "dept": "",
    "nbd": "",
    "progress": ""
  },
  {
    "priority": "",
    "customer": "",
    "requestor": "",
    "category": "",
    "model": "",
    "pn": "",
    "demand": "",
    "specification": "",
    "application": "",
    "dept": "",
    "nbd": "",
    "progress": ""
  },
  {
    "priority": "",
    "customer": "",
    "requestor": "",
    "category": "",
    "model": "",
    "pn": "",
    "demand": "",
    "specification": "",
    "application": "",
    "dept": "",
    "nbd": "",
    "progress": ""
  }
];